### ISSUE TITLE
Multiple identical models

### ISSUE THREAD

**Issue by hoxito** [carolinabentresca/Concesionaria#1]
Hi Carolina, I was taking a look at your Code and I noticed you have 4 Files (productos or ventas) with the exact same code. Could I ask what is this for?
Regards,
Jose aranciba.

**Comment by carolinabentresca** [comment]
Hi
They are just practice exercises.
Cheers 😁

**Comment by carolinabentresca** [comment]
There are 4 files ( productos / ventas)
Because each one represents a table (Entity) in my database..

**Comment by hoxito** [comment]
Oh okay! Thanks!
